version: "3.9"  # optional since v1.27.0
services:
  facesh_det_api:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    image: mindhive_facesh_det_api:v1
    volumes:
      - ..:/app
      - /dev/shm:/dev/shm
    environment:
      - TZ=Asia/Kuala_Lumpur
    container_name: facesh_det_api
    network_mode: host
    restart: always